### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by ronyfadel** [lucataco/cog-llama-2-7b-chat#1]
I get this when deploying on Replicate (playing around with the Replicate API)

**Comment by ronyfadel** [comment]
Full trace:

```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/cog/server/worker.py", line 185, in _setup
run_setup(self._predictor)
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/cog/predictor.py", line 66, in run_setup
predictor.setup()
File "/src/predict.py", line 22, in setup
model = AutoGPTQForCausalLM.from_quantized(
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/auto_gptq/modeling/auto.py", line 94, in from_quantized
return quant_func(
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 793, in from_quantized
accelerate.utils.modeling.load_checkpoint_in_model(
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1279, in load_checkpoint_in_model
checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1088, in load_state_dict
with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/cog/server/runner.py", line 292, in setup
    for event in worker.setup():
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/cog/server/worker.py", line 126, in _wait
    raise FatalWorkerException(raise_on_error + ": " + done.error_detail)
cog.server.exceptions.FatalWorkerException: Predictor errored during setup: Error while deserializing header: HeaderTooLarge
```

**Comment by lucataco** [comment]
Ah, have you tried to manually run line #30 in the file download-weights file? Not sure if it should be cloned via git-lfs, but 'cog run' doesn't seem to pull all the files from Llama-2-7b-Chat-GPTQ so I've had to clone it manually. You should be able to locally predict or deploy to Replicate just fine after that.

I left the commented code above line #30 just in case someone else is kind enough to fix it so it can download the quantized files in download-weights AND load them in the predict.py file correctly. But in the meantime, I resorted to git clone
